name: "How to generate QR Code of eLTER-RI by qrencoder package"
#show_downloads: true
url: https://oggioniale.github.io/LTERSitesQRCode/
github:
  zip_url: http://example.com/download.zip
  another_url: another value
params:
  year: 2019
  region: Europe
  printcode: TRUE
  # data: nameCoordsSites.csv, namCoordsNetwoks.csv
output_dir: "."
navbar:
  title: "Website"
  type: inverse
  left:
    - text: "Home"
      icon: fa-home
      href: index.html
    - text: "About"
      icon: fa-info
      href: about.html
  right:
    - icon: fa-question fa-lg
      href: https://example.com
output:
  html_document:
    theme: Slate
    toc: true  
    toc_float: true
    toc_depth: 2
    fig_width: 7
    fig_height: 5
    dev: png
    fig_caption: true
    includes:
      # in_header: header.html
      # before_body: doc_prefix.html
      after_body: doc_suffix.html
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/