name: "cars"
output_dir: "docs"
navbar:
  title: "Cars"
  left:
  - text: "Home"
   href: QRCodeGenerator.html
  - text: "Speed and Distance"
   href: speed-and-distance.html
output:
  html_document:
  theme: jekyll-theme-slate
