name: "How to generate QR Code of eLTER-RI by qrencoder package"
url: https://oggioniale.github.io/LTERSitesQRCode/
params:
  year: 2019
  region: Europe
  printcode: TRUE
  # data: nameCoordsSites.csv, namCoordsNetwoks.csv
output_dir: "."
navbar:
  title: "Website"
  type: inverse
  left:
    - text: "Home"
      icon: fa-home
      href: index.html
    - text: "About"
      icon: fa-info
      href: about.html
  right:
    - icon: fa-question fa-lg
      href: https://example.com
output:
  html_document:
    theme: Slate
    toc: true  
    toc_float: true
    toc_depth: 2
    fig_width: 7
    fig_height: 5
    dev: png
    fig_caption: true
    includes:
      # in_header: header.html
      # before_body: doc_prefix.html
      after_body: doc_suffix.html
theme: jekyll-theme-slate